server:
  port: 55556
spring:
  rabbitmq:
    host: 120.79.95.51
    port: 5672
    username: rabbitmq
    password: 123456
  cloud:
    bus:
      trace:
        enabled: true
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000