server:
  port: 55556
spring:
  rabbitmq:
    host: 120.79.95.51
    port: 5672
    username: rabbitmq
    password: 123456
  cloud:
    bus:
      trace:
        enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.0.202:40036/gateway?useSSL=false&serverTimezone=CTT&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 3396Zmr3Wj0VoflC
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 2000
      max-wait: 10000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      use-global-data-source-stat: true
      validation-query: SELECT 1
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000